FROM ubuntu:14.04

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y wget
RUN apt-get install -y zip
RUN apt-get install -y python-pip python-dev

RUN pip install numpy

#RUN apt-get -y install python-opencv
#RUN apt-get -y build-dep python-imaging
#RUN apt-get -y install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev
#RUN pip install Pillow

RUN mkdir -p /opt/chainerapp && mkdir -p /opt/t4j/chainerapp && mkdir -p /opt/t4j/chainerapp/mstimeges && mkdir -p /opt/t4j/chainerapp/imeges && mkdir -p /opt/t4j/chainerapp/tmpimages

RUN mkdir -p /opt/t4j/chainerapp && mkdir -p /var/opt/t4j/chainer-data/mstimeges && mkdir -p /var/opt/t4j/chainer-data/imeges && mkdir -p /var/opt/t4j/chainer-data/model && mkdir -p /var/opt/t4j/chainer-data/tmpimages

RUN echo "from numpy import *" > /opt/t4j/chainerapp/nurse_train_api.py && \
  echo "" >> /opt/t4j/chainerapp/nurse_train_api.py && \
  echo "def inspection():" >> /opt/t4j/chainerapp/nurse_train_api.py && \
  echo "    ret = array([[1,\"hengao\",25.8],[2,\"bad\",25.1],[3,\"drunken\",20.7],[4,\"excellent\",11.0],[5,\"normal\",4.0]])" >> /opt/t4j/chainerapp/nurse_train_api.py && \
  echo "    return ret" >> /opt/t4j/chainerapp/nurse_train_api.py && \
  echo "" >> /opt/t4j/chainerapp/nurse_train_api.py && \
  echo "if __name__ == \"__main__\":" >> /opt/t4j/chainerapp/nurse_train_api.py && \
  echo "    print inspection()" >> /opt/t4j/chainerapp/nurse_train_api.py
