FROM ubuntu:14.04

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y wget
RUN apt-get install -y zip
RUN apt-get install -y python-pip python-dev

RUN pip install numpy
RUN pip install Pillow

RUN mkdir -p /opt/chainerapp && mkdir -p /opt/t4j/chainerapp && mkdir -p /opt/t4j/chainerapp/dlbin && mkdir -p /opt/t4j/chainerapp/dockerbin && mkdir -p /opt/t4j/chainerapp/Dockerfiles && mkdir -p /opt/t4j/chainerapp/python
